# Generated by Django 6.0.1 on 2026-05-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(default='Unknown Company', max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
