# Generated by Django 6.0.1 on 2026-05-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='cv_profiles/'),
        ),
    ]
