# Generated by Django 6.0.1 on 2026-05-31 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='experience',
        ),
    ]
