# Generated by Django 6.0.1 on 2026-05-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_cv_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='cv_template',
            field=models.CharField(choices=[('modern', 'Modern'), ('europass', 'Europass'), ('minimal', 'Minimal')], default='modern', max_length=20),
        ),
    ]
