# Generated by Django 6.0.1 on 2026-05-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_cv_cv_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='cv_template',
        ),
        migrations.AddField(
            model_name='cv',
            name='template',
            field=models.CharField(default='modern', max_length=50),
        ),
    ]
