# Generated by Django 6.0.1 on 2026-05-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_cv_cv_template_cv_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='template',
            field=models.CharField(default='modern', max_length=30),
        ),
    ]
