# Generated by Django 6.0.1 on 2026-05-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_cv_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='template',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('europe', 'European Style')], default='modern', max_length=20),
        ),
    ]
