# Generated by Django 6.0.1 on 2026-05-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_cv_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='font_size',
            field=models.CharField(default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='cv',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='template',
            field=models.CharField(default='modern', max_length=20),
        ),
    ]
