# Generated by Django 6.0.1 on 2026-06-01 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_remove_experience_duration_experience_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('personal', 'Personal Info'), ('summary', 'Summary'), ('skills', 'Skills'), ('education', 'Education'), ('experience', 'Experience'), ('languages', 'Languages'), ('projects', 'Projects'), ('certifications', 'Certifications'), ('references', 'References')], max_length=30)),
                ('order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='jobs.cv')),
            ],
        ),
    ]
