# Generated by Django 6.0.1 on 2026-06-01 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_cvsection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvsection',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='cv',
            name='education',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='skills',
        ),
        migrations.AddField(
            model_name='certification',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='color',
            field=models.CharField(default='#4ca1af', max_length=20),
        ),
        migrations.AddField(
            model_name='cv',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cv',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='certification',
            name='organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='certification',
            name='year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cv',
            name='address',
            field=models.CharField(blank=True, default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cv',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cv',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cv',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='field',
            field=models.CharField(blank=True, default=11, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='listening',
            field=models.CharField(blank=True, choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient'), ('native', 'Native')], max_length=10),
        ),
        migrations.AlterField(
            model_name='language',
            name='reading',
            field=models.CharField(blank=True, choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient'), ('native', 'Native')], max_length=10),
        ),
        migrations.AlterField(
            model_name='language',
            name='speaking',
            field=models.CharField(blank=True, choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient'), ('native', 'Native')], max_length=10),
        ),
        migrations.AlterField(
            model_name='language',
            name='writing',
            field=models.CharField(blank=True, choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient'), ('native', 'Native')], max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reference',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reference',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reference',
            name='position',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
