# Generated by Django 6.0.1 on 2026-06-03 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_alter_cvsection_options_remove_cv_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('cv_file', models.FileField(upload_to='applications/')),
                ('cover_letter', models.TextField(blank=True)),
                ('match_score', models.IntegerField(blank=True, null=True)),
                ('matched_skills', models.TextField(blank=True)),
                ('missing_skills', models.TextField(blank=True)),
                ('experience_fit', models.CharField(blank=True, max_length=20)),
                ('verdict', models.CharField(blank=True, max_length=30)),
                ('ai_summary', models.TextField(blank=True)),
                ('interview_questions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-match_score', '-applied_at'],
            },
        ),
    ]
